/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author miwoj2051
 */
public class funWithLoops extends javax.swing.JFrame {

    /**
     * Creates new form funWithLoops
     */
    public funWithLoops() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        funWithLoops = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        startPrompt = new javax.swing.JLabel();
        startingValue = new javax.swing.JTextField();
        endPrompt = new javax.swing.JLabel();
        endingValue = new javax.swing.JTextField();
        showValues = new javax.swing.JButton();
        values = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(200, 70, 95));

        funWithLoops.setBackground(new java.awt.Color(250, 60, 5));
        funWithLoops.setForeground(new java.awt.Color(150, 70, 5));

        title.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        title.setText("Fun With Loops!");

        startPrompt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        startPrompt.setText("Enter a starting value:");

        startingValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startingValueActionPerformed(evt);
            }
        });

        endPrompt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        endPrompt.setText("Enter an ending value:");

        showValues.setText("Show Values");
        showValues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showValuesActionPerformed(evt);
            }
        });

        values.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout funWithLoopsLayout = new javax.swing.GroupLayout(funWithLoops);
        funWithLoops.setLayout(funWithLoopsLayout);
        funWithLoopsLayout.setHorizontalGroup(
            funWithLoopsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, funWithLoopsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(showValues)
                .addGap(124, 124, 124))
            .addGroup(funWithLoopsLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(funWithLoopsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(funWithLoopsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(funWithLoopsLayout.createSequentialGroup()
                            .addComponent(endPrompt)
                            .addGap(18, 18, 18)
                            .addComponent(endingValue))
                        .addGroup(funWithLoopsLayout.createSequentialGroup()
                            .addComponent(startPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(startingValue, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(values, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        funWithLoopsLayout.setVerticalGroup(
            funWithLoopsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(funWithLoopsLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(funWithLoopsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startPrompt)
                    .addComponent(startingValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(funWithLoopsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endPrompt)
                    .addComponent(endingValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showValues)
                .addGap(30, 30, 30)
                .addComponent(values, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(funWithLoops, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(funWithLoops, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startingValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startingValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startingValueActionPerformed

    private void showValuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showValuesActionPerformed
        double startNum, endNum;
        int value;
        String allValues= "";
              
        startNum = Double.parseDouble(startingValue.getText());
        endNum = Double.parseDouble(endingValue.getText());
        
      for ( int i=(int)startNum; i<(int)endNum; i++){
          allValues+= i;
      }
        
           values.setText("Numbers are " + allValues); 
         
        
    }//GEN-LAST:event_showValuesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(funWithLoops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(funWithLoops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(funWithLoops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(funWithLoops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new funWithLoops().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel endPrompt;
    private javax.swing.JTextField endingValue;
    private javax.swing.JPanel funWithLoops;
    private javax.swing.JButton showValues;
    private javax.swing.JLabel startPrompt;
    private javax.swing.JTextField startingValue;
    private javax.swing.JLabel title;
    private javax.swing.JLabel values;
    // End of variables declaration//GEN-END:variables
}
